name: .NET Release on tag push

on:
  push:
    tags:
      - "V*.*.*"

jobs:
  publish_and_release:

    runs-on: windows-latest

    steps:
# ---- Checkout main source code
      - name: Checkout
        uses: actions/checkout@v3

# ---- Get submodules
      - name: Checkout submodules
        run: git submodule update --init --recursive
      
      
# ---- CSPROJ Version preparations

      - name: Get csproj version
        uses: kzrnm/get-net-sdk-project-versions-action@v1
        id: get-version
        with:
          proj-path: ./martridge/src/martridge.csproj


# ---- .NET Preparations

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./martridge/src/martridge.csproj
      
# ---- Publish and archive - net8.0 win-x86
      - name: Clean before publish
        run: dotnet clean ./martridge/martridge.sln --configuration Release -p:Platform="x86" --framework net8.0
      - name: Publish net8.0 win-x86
        run: dotnet publish ./martridge/src/martridge.csproj --output ./publish/net8.0_win-x86/martridge/ --configuration Release -p:Platform="x86" --framework net8.0 --runtime win-x86 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
      - name: Archive published net8.0 win-x86
        uses: ihiroky/archive-action@v1
        with:
          root_dir: "./publish/net8.0_win-x86/"
          file_path: "./publish/martridge_V${{steps.get-version.outputs.version}}_net8.0_win-x86.zip"



# ---- Publish and archive - net8.0 win-x64
      - name: Clean before publish
        run: dotnet clean ./martridge/martridge.sln --configuration Release -p:Platform="x64" --framework net8.0
      - name: Publish net8.0 win-x64
        run: dotnet publish ./martridge/src/martridge.csproj --output ./publish/net8.0_win-x64/martridge/ --configuration Release -p:Platform="x64" --framework net8.0 --runtime win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
      - name: Archive published net8.0 win-x64
        uses: ihiroky/archive-action@v1
        with:
          root_dir: "./publish/net8.0_win-x64/"
          file_path: "./publish/martridge_V${{steps.get-version.outputs.version}}_net8.0_win-x64.zip"


# ---- Publish and archive - net8.0 linux-x64
      - name: Clean before publish
        run: dotnet clean ./martridge/martridge.sln --configuration Release -p:Platform="Any CPU" --framework net8.0
      - name: Publish net8.0 linux-x64
        run: dotnet publish ./martridge/src/martridge.csproj --output ./publish/net8.0_linux-x64/martridge/ --configuration Release -p:Platform="Any CPU" --framework net8.0 --runtime linux-x64 --self-contained true -p:PublishSingleFile=true
      - name: Archive published net8.0 linux-x64
        uses: ihiroky/archive-action@v1
        with:
          root_dir: "./publish/net8.0_linux-x64/"
          file_path: "./publish/martridge_V${{steps.get-version.outputs.version}}_net8.0_linux-x64.tar.gz"
      
      
# for now, i added osx publish configs but i'm not using them

# ---- Publish and archive - net8.0 osx-x64
#      - name: Clean before publish
#        run: dotnet clean ./martridge/martridge.sln --configuration Release -p:Platform="Any CPU" --framework net8.0
#      - name: Publish net8.0 osx-x64
#        run: dotnet publish ./martridge/src/martridge.csproj --output ./publish/net8.0_osx-x64/martridge/ --configuration Release -p:Platform="Any CPU" --framework net8.0 --runtime osx-x64 --self-contained true -p:PublishSingleFile=true
#      - name: Archive published net8.0 osx-x64
#        uses: ihiroky/archive-action@v1
#        with:
#          root_dir: "./publish/net8.0_osx-x64/"
#          file_path: "./publish/martridge_V${{steps.get-version.outputs.version}}_net8.0_osx-x64.tar.gz"


# ---- Publish and archive - net8.0 osx-arm64
#      - name: Clean before publish
#        run: dotnet clean ./martridge/martridge.sln --configuration Release -p:Platform="Any CPU" --framework net8.0
#      - name: Publish net8.0 osx-arm64
#        run: dotnet publish ./martridge/src/martridge.csproj --output ./publish/net8.0_osx-arm64/martridge/ --configuration Release -p:Platform="Any CPU" --framework net8.0 --runtime osx-arm64 --self-contained true -p:PublishSingleFile=true
#      - name: Archive published net8.0 osx-arm64
#        uses: ihiroky/archive-action@v1
#        with:
#          root_dir: "./publish/net8.0_osx-arm64/"
#          file_path: "./publish/martridge_V${{steps.get-version.outputs.version}}_net8.0_osx-arm64.tar.gz"


# ---- Creating github Release

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: "Automatic release for version V${{steps.get-version.outputs.version}}"
          token: ${{github.token}}
          repository: ${{github.repository}}
          files: |
            ./publish/martridge_V${{steps.get-version.outputs.version}}_net8.0_win-x86.zip
            ./publish/martridge_V${{steps.get-version.outputs.version}}_net8.0_win-x64.zip
            ./publish/martridge_V${{steps.get-version.outputs.version}}_net8.0_linux-x64.tar.gz
# for now, do not publish osx builds...
#            ./publish/martridge_V${{steps.get-version.outputs.version}}_net8.0_osx-x64.tar.gz
#            ./publish/martridge_V${{steps.get-version.outputs.version}}_net8.0_osx-arm64.tar.gz
